
"$schema" = "https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/bunfig.json"

[test]
coverageSkipTestFiles = true
coveragePathIgnorePatterns = ["/lib/", "/dist/", "/node_modules/", "AppData"]
